"""Async SQLAlchemy engine and session factory."""

from __future__ import annotations

from collections.abc import AsyncGenerator

from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from app.core.config import settings

_url = settings.DATABASE_URL
# SQLite (used in tests) uses a different pool implementation than Postgres and
# does not accept these pool-sizing kwargs, so only pass them for real backends.
_pool_kwargs = (
    {}
    if _url.startswith("sqlite")
    else {
        "pool_size": settings.DB_POOL_SIZE,
        "max_overflow": settings.DB_MAX_OVERFLOW,
        "pool_recycle": settings.DB_POOL_RECYCLE_SECONDS,
        "pool_timeout": settings.DB_POOL_TIMEOUT,
    }
)

_engine: AsyncEngine = create_async_engine(
    _url,
    echo=settings.DEBUG,
    pool_pre_ping=True,
    future=True,
    **_pool_kwargs,
)

SessionFactory = async_sessionmaker(bind=_engine, expire_on_commit=False, class_=AsyncSession)


def get_engine() -> AsyncEngine:
    return _engine


async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """FastAPI dependency yielding a transactional session.

    Commits once, at the request boundary, on success; rolls back on any
    exception. Services and routes must not call ``commit()`` themselves —
    they should ``flush()`` when a later step in the same request needs to
    see a write (e.g. an autogenerated id or a uniqueness check).
    """
    async with SessionFactory() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
