"""composite indexes

Revision ID: 7f751a27a5ad
Revises: 7cdc29eb5f85
Create Date: 2026-07-15 08:32:10.934962
"""

from collections.abc import Sequence

from alembic import op

revision: str = "7f751a27a5ad"
down_revision: str | None = "7cdc29eb5f85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_email_tokens_user_purpose", "email_tokens", ["user_id", "purpose"], unique=False
    )
    op.create_index(
        "ix_sessions_user_active_activity",
        "sessions",
        ["user_id", "is_active", "last_activity_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sessions_user_active_activity", table_name="sessions")
    op.drop_index("ix_email_tokens_user_purpose", table_name="email_tokens")
    # ### end Alembic commands ###
