"""add sessions table

Revision ID: a55f82d64171
Revises: b3d383eed5ef
Create Date: 2026-07-14 07:42:36.309943
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.types import GUID

revision: str = "a55f82d64171"
down_revision: str | None = "b3d383eed5ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("session_uuid", GUID(), nullable=False),
        sa.Column("refresh_token_id", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=128), nullable=False),
        sa.Column("device_type", sa.String(length=32), nullable=False),
        sa.Column("browser", sa.String(length=64), nullable=False),
        sa.Column("browser_version", sa.String(length=32), nullable=False),
        sa.Column("operating_system", sa.String(length=64), nullable=False),
        sa.Column("operating_system_version", sa.String(length=32), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("login_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("logout_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("logout_reason", sa.String(length=64), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_is_active"), "sessions", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_sessions_refresh_token_id"), "sessions", ["refresh_token_id"], unique=False
    )
    op.create_index(op.f("ix_sessions_session_uuid"), "sessions", ["session_uuid"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_session_uuid"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_refresh_token_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_is_active"), table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
